# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@0.1.3

jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    environment:
          CIRCLECI: 1

    working_directory: ~/repo

    steps:
      - checkout
      
      - browser-tools/install-browser-tools

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m pytest application/tests
            coverage run -m pytest
            codecov

      - run:
          name: start server for tests
          command: |
            . venv/bin/activate
            python3 run.py
          background: true

      - run:
          name: run behave tests
          command: |
            . venv/bin/activate
            behave application/tests/features/

      - store_artifacts:
          path: test-reports
          destination: test-reports
